---
title: "Mini_project2"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

```{r,include = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(base)
library(ggmap)
library(maps)
library(mapdata)
library(lubridate)
```


```{r, message = FALSE, warning = FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r, message = FALSE, warning = FALSE}
# Define the function that convert the state abbreviation to state's full name
state_full_name <-function(x) {
  state_df <- data.frame(
     abb = c("","AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
             "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME",
             "MI", "MN", "MO", "MS",  "MT", "NC", "ND", "NE", "NH", "NJ", "NM",
             "NV", "NY", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN",
             "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"),
     full_name = c("","alaska","alabama","arkansas","arizona","california","colorado",
                   "connecticut","district of columbia","delaware","florida","georgia",
                   "hawaii","iowa","idaho","illinois","indiana","kansas","kentucky",
                   "louisiana","massachusetts","maryland","maine","michigan","minnesota",
                   "missouri","mississippi","montana","north carolina","north dakota",
                   "nebraska","new hampshire","new jersey","new mexico","nevada",
                   "new york","ohio","oklahoma","oregon","pennsylvania","puerto rico",
                   "rhode island","south carolina","south dakota","tennessee","texas",
                   "utah","virginia","vermont","washington","wisconsin",
                   "west virginia","wyoming")
 )
  index <- as.numeric(which(state_df$abb == x))
  return(as.character(state_df[index,2]))
  
}
```


```{r, fig.width = 12, fig.height = 7, message = FALSE, warning = FALSE}
#glimpse(house_elections)
#glimpse(candidates)
#glimpse(committees)
#glimpse(contributions)

# Filter out the candidate data that is only for 2012 elections 
# Change the "REP" and "DEM" to "R" and "D" respectively
candidate_2012 <- candidates %>%
  filter(cand_election_yr == 2012) %>%
  mutate(cand_party_affiliation = gsub("REP", "R", cand_party_affiliation),
         cand_party_affiliation = gsub("DEM", "D", cand_party_affiliation))
candidate_2012$cand_state <- as.character(candidate_2012$cand_state)

contributions$transaction_dt <- as.Date(contributions$transaction_dt, "%m%d%Y")
contributions$transaction_amt <- as.numeric(contributions$transaction_amt)

# Normally, presidential election starts the fundrasiign 15-20 months before the election.
# Conservatively we take all the donation two years before the election into account 

# Filter out all contribution that is "Independent expenditure advocating/opposing election of candidate"
# There are some 0 and negative amount and we will filter out those values and only consider the positive values 
contributions_2012 <- contributions %>%
  filter(transaction_dt >= "2010-11-06" & transaction_dt <= "2012-11-06") %>%
  filter(transaction_amt > 0 & transaction_type == "24E") %>%
  group_by(cand_id) %>%
  summarize(total_donation = sum(transaction_amt))

candidate_contributions_2012 <- contributions_2012 %>%
  inner_join(candidate_2012, by="cand_id") 

candidate_contributions_2012_rep <- candidate_contributions_2012 %>%
   filter(cand_party_affiliation == "R") %>%
   group_by(cand_state) %>%
   summarize(state_donation = sum(total_donation)) 
candidate_contributions_2012_rep$cand_state <- lapply(candidate_contributions_2012_rep$cand_state, FUN = state_full_name)
candidate_contributions_2012_rep$cand_state <- as.character(candidate_contributions_2012_rep$cand_state)

candidate_contributions_2012_dem <- candidate_contributions_2012 %>%
   filter(cand_party_affiliation == "D") %>%
   group_by(cand_state) %>%
   summarize(state_donation = sum(total_donation))
candidate_contributions_2012_dem$cand_state <- lapply(candidate_contributions_2012_dem$cand_state, FUN = state_full_name)
candidate_contributions_2012_dem$cand_state <- as.character(candidate_contributions_2012_dem$cand_state)

states <- map_data("state")
#head(states)
states$cand_state <- states$region
#head(states)
map_rep <- inner_join(states, candidate_contributions_2012_rep, by ="cand_state")
map_dem <- inner_join(states, candidate_contributions_2012_dem, by ="cand_state")


rep <- ggplot()
rep <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(color = "grey87", fill = "grey87")

rep <- rep + 
      geom_polygon(data = map_rep, aes(fill = state_donation)) +
      theme(axis.title = element_blank(),
            axis.text = element_blank(),
            axis.line = element_blank(),
            axis.ticks = element_blank(),
            panel.background = element_blank(),
            panel.grid = element_blank(), 
            panel.border = element_blank(), 
            text = element_text(size=15, face = "bold", color = "black")) + 
      labs(title = "Republican Donations in US 2012 Election (By States)", 
           caption = "Source: Federal Election Commission") + 
      scale_fill_gradient(low="mistyrose1", high="brown3", trans = "log",
                          name = "State Donations", breaks = c(100,3000, 170000, 9000000),
                           labels = c("100","3000", "170000","9000000"))+
      theme(legend.title = element_text(colour="red4", size=15, face="bold"))
  
rep


dem <- ggplot()
dem <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(color = "grey87", fill = "grey87")

dem <- dem + 
      geom_polygon(data = map_dem, aes(fill = state_donation)) +
      theme(axis.title = element_blank(),
            axis.text = element_blank(),
            axis.line = element_blank(),
            axis.ticks = element_blank(),
            panel.background = element_blank(),
            panel.grid = element_blank(), 
            panel.border = element_blank(), 
            text = element_text(size=15, face = "bold", color = "black")) + 
      labs(title = "Democratic Donations in US 2012 Election (By States)", 
           caption = "Source: Federal Election Commission") +
      scale_fill_gradient(low="lightblue1", high="royalblue4", trans = "log",
                          name = "State Donations", breaks = c(100,5000, 300000,20000000),
                          labels = c("100","5000","300000","20000000"))+
      theme(legend.title = element_text(colour="navy", size=15, face="bold"))
    
dem
```

```{r, fig.width = 10, fig.height = 6, message = FALSE, warning = FALSE}
contributions_state <- contributions %>%
  filter(transaction_dt >= "2011-11-06" & transaction_dt <= "2012-11-06") %>%
  filter(transaction_amt > 0 & transaction_type == "24E") 

candidate_contributions_state <- contributions_state %>%
  inner_join(candidate_2012, by="cand_id") %>%
  filter(cand_party_affiliation == "R" | cand_party_affiliation == "D") %>%
  group_by(cand_state) %>%
  filter(n_distinct(cand_party_affiliation) == 2) %>%
  group_by(cand_state,cand_party_affiliation) %>%
  summarize(total_donation = sum(transaction_amt)) 

candidate_contributions_state$total_donation <- sqrt(candidate_contributions_state$total_donation)

candidate_contributions_state$cand_state[candidate_contributions_state$cand_state == ""] <- "Other"
candidate_contributions_state$total_donation <- ifelse(candidate_contributions_state$cand_party_affiliation == "R", 
                                                       -1 * candidate_contributions_state$total_donation,
                                                       candidate_contributions_state$total_donation)

gg <- ggplot(data = candidate_contributions_state, aes(x = cand_state, y = total_donation, fill = cand_party_affiliation)) + 
	    geom_bar(stat="identity", position="identity") +
      theme(axis.line = element_blank(),
            panel.border = element_blank(), 
            text = element_text(size=10, face = "bold", color = "black")) +
      labs(x = "Candidate State", y = "State Donation") +
      scale_fill_manual(breaks = c("Democratic", "Republican"), 
                       values=c("royalblue3","brown3")) +
      theme(legend.title = element_text(colour="black", size=15, face="bold"), 
            panel.background = element_rect(fill = "grey90",
                                colour = "grey90",
                                size = 0.5, linetype = "solid")) +
      annotate(geom="text", x = c("TX", "TX"), y = c(5000, -7500), 
               label = c("Democratic", "Republican"), 
               size = 11, color = c("royalblue3","brown3"), fontface = 'bold')
      
  
gg
```

